config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :frnds
  #get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #root 'home#index'
  get 'home/about'
  
  root 'frnds#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class = true
end

app/models/frnd.rb
class Frnd < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :frnds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/frnds_controller.rb
class FrndsController < ApplicationController
  before_action :set_frnd, only: [:show, :edit, :update, :destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /frnds or /frnds.json
  def index
    @frnds = Frnd.all
  end

  # GET /frnds/1 or /frnds/1.json
  def show
  end

  # GET /frnds/new
  def new
    @frnd = current_user.frnds.build
  end

  # GET /frnds/1/edit
  def edit
  end
  
  # POST /frnds or /frnds.json
  def create
    @frnd = current_user.frnds.build(frnd_params)

    respond_to do |format|
      if @frnd.save
        format.html { redirect_to @frnd, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @frnd }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @frnd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frnds/1 or /frnds/1.json
  def update
    respond_to do |format|
      if @frnd.update(frnd_params)
        format.html { redirect_to @frnd, notice: "Frnd was successfully updated." }
        format.json { render :show, status: :ok, location: @frnd }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @frnd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frnds/1 or /frnds/1.json
  def destroy
    @frnd.destroy
    respond_to do |format|
      format.html { redirect_to frnds_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @frnd = current_user.frnds.find_by(id: params[:id])
    redirect_to frnds_path, notice: "Not Authorized To Edit This Friend" if @frnd.nil?
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frnd
      @frnd = Frnd.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def frnd_params
      params.require(:frnd).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_me = "My Name is Kritika Jain"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/frnds_helper.rb
module FrndsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/frnds/_form.html.erb
<%= form_with(model: frnd) do |form| %>
  <% if frnd.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(frnd.errors.count, "error") %> prohibited this frnd from being saved:</h2>

      <ul>
        <% frnd.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    
    <%= form.text_field :first_name, class: "form-control", placeholder:"First Name" %>
  </div>
  <br>
  <div class="field form-group">
    
    <%= form.text_field :last_name, class: "form-control", placeholder:"Last Name" %>
  </div>
  <br>

  <div class="form-group">
    
    <%= form.text_field :email, class: "form-control", placeholder: "Email" %>
  </div>
  <br>

  <div class="form-group">
    
    <%= form.text_field :phone, class: "form-control", placeholder:"Phone Number" %>
  </div>
  <br>

  <div class="form-group">
    
    <%= form.text_field :twitter, class: "form-control", placeholder:"Twitter" %>
  </div>

  <div class="form-group">
    
    <%= form.number_field :user_id, id: :frnds_user_id, class: "form-control", placeholder:"User Id", value: current_user.id, type: :hidden  %>
    
  </div>
  <br>
  <div>
    <%= form.submit class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/frnds/_frnd.html.erb
<div id="<%= dom_id frnd %>">
  <p>
    <strong>First name:</strong>
    <%= frnd.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= frnd.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= frnd.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= frnd.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= frnd.twitter %>
  </p>

</div>

app/views/frnds/edit.html.erb
<h1>Edit Friend</h1>
<br>
<%= render "form", frnd: @frnd %>

<br>

<div >
  <div class="btn-group me-2" role="group" aria-label="First group">
    <%= link_to "Show", @frnd, class:"btn btn-secondary" %> 
  </div>
  <div class="btn-group me-2" role="group" aria-label="Second group">
    <%= button_to "Delete", @frnd, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
  </div>
  <%= link_to "Back", frnds_path, class:"btn btn-dark" %>
</div>

app/views/frnds/index.html.erb
<% if user_signed_in? %>
  <table class="table table-striped table-bordered table-hover">
    <thead class="table-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
        <th ></th>
      </tr>
    </thead>
    <tbody>
      <% @frnds.each do |frnd| %>
        <% if frnd.user == current_user %>
        <tr>
          <td><%= link_to frnd.first_name + ' ' + frnd.last_name, frnd_path(frnd) %> </td>
          <td><%= frnd.email %></td>
          <td><%= frnd.phone %></td>
          <td><%= frnd.twitter %></td>
          
          <% if frnd.user == current_user %>
            <td><%= link_to "Delete", frnd, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
            
          <% end %>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to "New friend", new_frnd_path, class:"btn btn-secondary" %>
<% else %>
<h1>Welcome</h1>
This is my first Rails webpage....
<% end %>

app/views/frnds/new.html.erb
<h1>Add New Friend</h1>

<%= render "form", frnd: @frnd %>

<br>

<div>
  <%= link_to "Back", frnds_path, class: "btn btn-dark" %>
</div>

app/views/frnds/show.html.erb
<%= render @frnd %>

<div>
  <div class="btn-group me-2" role="group" aria-label="First group">
    <%= link_to "Edit", edit_frnd_path(@frnd), class:"btn btn-secondary" %>
  </div>
  <div class="btn-group me-2" role="group" aria-label="Second group"> 
    <%= button_to "Delete", @frnd, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %>
  </div>
  <%= link_to "Back", frnds_path, class:"btn btn-secondary" %>

</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">
  	<%= link_to "Friend App", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
        	<%= link_to "About Us" , home_about_path, class: "nav-link" %>
        </li>
        

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Add Friend" , new_frnd_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile" , edit_user_registration_path, class: "nav-link" %>
          </li>
        <% else %>

          <li class="nav-item">
            <%= link_to "Sign Up" , new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In" , new_user_session_path, class: "nav-link" %>
          </li> 
        <% end %>
        
        
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About me....</h1>
<p>
	<%= @about_me %>
</p>

app/views/home/index.html.erb
<h1>Welcome</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friend's App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
    <br>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
      <br>
      <%= yield %>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>